name: CI

on:
  push:
    branches: [ test_master ]
  pull_request:
    branches: [ test_master ]
  release:
    types: [ published ]

jobs:
  build:
    name: ${{ matrix.target }} (${{ matrix.host.name }})
    runs-on: ${{ matrix.host.build }}

    strategy:
      fail-fast: false
      matrix:
        host:
        - name: linux-x86_64
          build: ubuntu-18.04
        - name: macos-x86_64
          build: macos-10.15
        - name: windows-x86_64
          build: ubuntu-18.04
        target:
        - aarch64-zephyr-elf

    steps:
    # Set up build environment (Linux build system)
    - name: Install dependency packages for Linux
      if: ${{ matrix.host.build == 'ubuntu-18.04' }}
      run: |
        sudo apt-get install bison flex gettext help2man libncurses5-dev \
                             libtool-bin libtool-doc texinfo

        if [ "${{ matrix.host.name }}" == "windows-x86_64" ]; then
          sudo apt-get install binutils-mingw-w64 gcc-mingw-w64 g++-mingw-w64
        fi

    # Set up build environment (macOS build system)
    - name: Install dependency packages for macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install autoconf automake bash binutils gawk gnu-sed gnu-tar \
                     help2man ncurses

    - name: Create case sensitive workspace volume for macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        hdiutil create ${HOME}/Workspace.sparseimage -volname Workspace -type SPARSE -size 14g -fs HFSX
        hdiutil mount ${HOME}/Workspace.sparseimage

    # Check out source code
    - name: Check out source code
      uses: actions/checkout@v2

    # Fetch all history for all tags and branches
    - run: git fetch --prune --unshallow --tags --force

    # Build crosstool-ng
    - name: Build crosstool-ng
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          export PATH="$PATH:/usr/local/opt/binutils/bin"
          export CPPFLAGS="-I/usr/local/opt/ncurses/include -I/usr/local/opt/gettext/include"
          export LDFLAGS="-L/usr/local/opt/ncurses/lib -L/usr/local/opt/gettext/lib"
        fi

        ./bootstrap
        ./configure --prefix=${HOME}/crosstool-ng
        make
        make install

    - name: Test crosstool-ng
      run: |
        ${HOME}/crosstool-ng/bin/ct-ng version

    # Build toolchain
    - name: Build ${{ matrix.target }} toolchain for ${{ matrix.host.name }}
      run: |
        export CT_NG="${HOME}/crosstool-ng/bin/ct-ng"

        # Resolve GNU tar name
        if [ "$RUNNER_OS" == "macOS" ]; then
          export TAR="gtar"
        else
          export TAR="tar"
        fi

        # Resolve workspace path
        if [ "$RUNNER_OS" == "macOS" ]; then
          export WORKSPACE="/Volumes/Workspace"
        else
          export WORKSPACE="${HOME}"
        fi

        # Create output directory
        export CT_PREFIX="${WORKSPACE}/output"
        mkdir -p ${CT_PREFIX}

        # Create build directory
        mkdir -p ${WORKSPACE}/build
        pushd ${WORKSPACE}/build

        # Load default target configurations
        ${CT_NG} ${{ matrix.target }}

        # Set build configurations
        cat <<EOF >> .config
        CT_CLEAN_AFTER_BUILD_STEP=y
        EOF

        # Set logging configurations
        cat <<EOF >> .config
        CT_LOG_PROGRESS_BAR=n
        CT_LOG_EXTRA=n
        CT_LOG_ALL=y
        CT_LOG_LEVEL_MAX="ALL"
        EOF

        # Set Windows Canadian cross compilation configurations
        if [ "${{ matrix.host.name }}" == "windows-x86_64" ]; then
          cat <<EOF >> .config
        CT_CANADIAN=y
        CT_HOST="x86_64-w64-mingw32"
        CT_GDB_CROSS_PYTHON=n
        EOF
        fi

        # Merge configurations
        ${CT_NG} savedefconfig DEFCONFIG=build.config
        ${CT_NG} distclean
        ${CT_NG} defconfig DEFCONFIG=build.config

        # Build
        ${CT_NG} build
        popd

        # Resolve output directory path
        if [ "${{ matrix.host.name }}" == "windows-x86_64" ]; then
          export OUTPUT_BASE="${WORKSPACE}/output"
          export OUTPUT_DIR="HOST-x86_64-w64-mingw32"
        else
          export OUTPUT_BASE="${WORKSPACE}"
          export OUTPUT_DIR="output"
        fi

        # Rename output directory if release build
        if [ "${{ github.event_name }}" == "release" ]; then
          mv ${OUTPUT_BASE}/${OUTPUT_DIR} ${OUTPUT_BASE}/${{ github.event.release.tag_name }}
          export OUTPUT_DIR="${{ github.event.release.tag_name }}"
        fi

        # Move build log file out of workspace
        mv ${OUTPUT_DIR}/${{ matrix.target }}/build.log.bz2 \
           ${{ matrix.target }}.log.bz2

        # Create archive
        ${TAR} -zcvf --owner=0 --group=0 ${{ matrix.target }}.tar.gz
               -C ${OUTPUT_BASE} ${OUTPUT_DIR}

    # Upload build log
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: log_${{ matrix.host.name }}_${{ matrix.target }}
        path: ${{ matrix.target }}.log.bz2

    # Upload build artifact
    - name: Upload build artifact
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v2
      with:
        name: toolchain_${{ matrix.host.name }}_${{ matrix.target }}
        path: ${{ matrix.target }}.tar.gz

    # Upload release asset
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.target }}.tar.gz
        asset_name: ${{ github.event.release.tag_name }}_${{ matrix.host.name }}_${{ matrix.target }}.tar.gz
        asset_content_type: application/gzip
